version: '3'
services:
  jupyter:
      build:
        context: .
        dockerfile: Dockerfile.jupyter
      container_name: cards2flash_jupyter
      ports:
        - "8888:8888"
      volumes:
        - .:/home/jovyan/app
      environment:
        - JUPYTER_ENABLE_LAB=yes
      env_file:
            - .env