workflow_name: "Vocabulary Extraction and Flashcard Generation"

user_inputs: [deckname]

# 1) **Scrape Notes from Google Docs**
scrape_notes:
  - url: "https://docs.google.com/document/d/1VX_86MHD9BtyjdjAb8QZfF457H55MI_xy2M5_1zFuYw/edit?tab=t.0"
    output: scraped_notes_output  # Only specifying the output name

# 2) **Process Notes into Flashcards**
process_notes_to_cards:
  - step: "Process notes and create flashcards"
    model: "openai/gpt-4o-mini"
    chunk_size: 4000  # Maximum chars per chunk (roughly 4 * token limit for english, 1*token_limit for mandarin)
    input:
      - scraped_notes_output  # Input is the notes content from Google Docs
    attach_format_reminder: True # If true will append a format reiminder to the prompt ensuring API outputs correct format
    output: flashcards  # The output should always be a list of dictionaries with the following fields:
    output_fields:
      - mandarin
      - pinyin
      - translation
    prompt: |
      Review the following Mandarin notes document and extract vocabulary that would be useful for a language learner. 
      Translate each selected vocabulary word into English to aid comprehension.

      For each vocabulary word:

          Include the Mandarin word.
          Provide the Pinyin pronunciation.
          Offer an English translation that best conveys the meaning in a learning context.

      Focus on selecting relevant terms that a learner should prioritize for study and comprehension. 

      Document Notes:
      {scraped_notes_output} 
     
#  3)  **Add Cards to Anki**
add_cards_to_anki:
  flashcards_data: flashcards  # Input is the list of flashcards
  deck_name: "{deckname}"
  card_template:
    template_name: "Notes2Flash Basic Note Type" # 'Notes2Flash Basic Note Type' is a default note type included in addon found in ./included_note_types/
    front: "{mandarin}"
    back: "{pinyin}<br><br>{translation}"
