workflow_name: "General Notes Organization and Flashcard Generation"

user_inputs: [google_doc_id, topic, deckname]

# 1) **Scrape Notes from Google Docs**
scrape_notes:
  - doc_id: "{google_doc_id}"
    output: scraped_notes_output  # The output name for the scraped notes

# 2) **Process Notes into Flashcards**
process_notes_to_cards:
  - step: "Organize notes and create flashcards"
    model: "meta-llama/llama-3.1-8b-instruct:free"
    input:
      - scraped_notes_output  # Input is the notes content from Google Docs
      - topic  # Input is the topic of the notes for organizing
    output: flashcards  # The output will always be a list of dictionaries with the following fields:
    output_fields:
      - question
      - answer
    prompt: |
      Organize the following notes on the topic "{topic}" to help with revision:
      {scraped_notes_output} 
      For each note, create a flashcard using the exact format below, where the key for the question should be "question" and the key for the answer should be "answer".
      Do not use any other keys or formats.

      Output flashcards in this format:
      [
        {"question": "question1", "answer": "answer1"},
        {"question": "question2", "answer": "answer2"},
        ...
      ]

#  3)  **Add Cards to Anki**
add_cards_to_anki:
  flashcards_data: flashcards  # Input is the list of flashcards
  deck_name: "{deckname}"
  card_template:
    template_name: "Basic"
    front: "{question}"  # The front of the card will show the question
    back: "{answer}"  # The back of the card will show the answer