workflow_name: "Vocabulary Extraction and Multi-step Processing"

user_inputs: [google_doc_id, deckname]

# 1) **Scrape Notes from Google Docs**
scrape_notes:
  - doc_id: "{google_doc_id}"
    output: scraped_notes_output

# 2) **Process Notes (Multiple Steps)**
process_notes_to_cards:
  - step: "Extract key sentences"
    model: "openai/gpt-4o-mini"
    chunk_size: 4000
    input:
      - scraped_notes_output
    output: extracted_keywords  # Intermediate output
    prompt: |
    prompt: |
      Extract keywords from the following document. The document contains vocabulary words or short phrases in Mandarin. For each keyword, provide its pinyin and English translation. Remove any irrelevant information or duplicates. If there are multiple valid translations for a keyword, choose the most common one.

      Output in the following format:
      [
        {"keyword": "word1", "pinyin": "pinyin1", "translation": "translation1"},
        {"keyword": "word2", "pinyin": "pinyin2", "translation": "translation2"},
        ...
      ]

      Document:
      {scraped_notes_output}   
 
    
  - step: "Generate flashcards"
    model: "openai/gpt-4o-mini"
    chunk_size: 4000
    input:
      - extracted_keywords  # Input is the extracted keywords
    output: flashcards  # Final output
    output_fields:
      - sentence
      - keywords
    prompt: |
      For each group of related keywords below, generate an example sentence in Mandarin that uses one or more of the keywords appropriately. Ensure the sentence is natural and contextually accurate. Provide the pinyin and English translation for each sentence.

      Additionally, list the keywords used in the sentence in the format: "keyword pinyin translation," using `<br>` as a separator if multiple keywords are included.

      **Important**: The output must be in JSON format where each dictionary has exactly these two keys: "sentence" and "keywords". Do not change these keys.

      Format the output exactly like this:
      [
        {"sentence": "Here goes the example sentence.", "keywords": "keyword1 pinyin1 translation1<br>keyword2 pinyin2 translation2"},
        {"sentence": "Another example sentence.", "keywords": "keywordA pinyinA translationA<br>keywordB pinyinB translationB"},
        ...
      ]

      Keywords:
      {extracted_keywords}
   
#  3)  **Add Cards to Anki**
add_cards_to_anki:
  flashcards_data: flashcards  # Input is the list of flashcards
  deck_name: "{deckname}"
  card_template:
    template_name: "Basic"
    front: "{sentence}"
    back: "{keywords}"
