version: '3'
services:
  # Docker service to copy the anki_config directory and the addon directory into the Anki container
  copy-anki-config:
    image: alpine:latest
    working_dir: /app
    volumes:
      - ../anki_config:/app/anki_config  # Relative path to anki_config
      - ../../addon:/app/addon  # Relative path to the addon directory
      - anki_data:/config
    command: sh -c "
      mkdir -p /config/app/Anki2/User\ 1/backups /config/app/Anki2/addons21/notes2flash_addon &&  
      echo 'Checking files in /app/anki_config:' && ls -l /app/anki_config &&  
      echo 'Checking files in /app/addon:' && ls -l /app/addon &&  
      cp -r /app/anki_config/* /config/app/Anki2/ && 
      cp -r /app/addon/* /config/app/Anki2/addons21/notes2flash_addon/ && 
      echo 'Files copied successfully'"


  # Docker service to run Anki for development
  anki-desktop:
    build:
      context: .  # Set the build context to the current directory
      dockerfile: Dockerfile.anki
    volumes:
      - anki_data:/config/app/Anki2
      - ../anki_backups:/config/app/backups  # Relative path to anki_backups
    ports:
      - 3000:3000
      - 8765:8765
    depends_on:
      - copy-anki-config

volumes:
  anki_data:


